site_name: Re:Crude Docs
site_description: "Technical Documentation for the Re:Crude App"
site_url:
repo_name: Re:Crude
repo_url: https://github.com/manav-gkmit/re-crude-docs

theme:
  name: material
  icon: 
    logo: material/card-account-mail-outline
    repo: simple/github
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb-off
        name: Switch to system preference
  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption


nav:
  - Home: index.md
  - Requirements: requirements.md
  - Architecture: architecture.md
  - Technology Stack: tech-stack.md
  - Modules:
      - Zoho Polling & Batch Manager: modules/zoho_polling.md
      - Resume Processing & Queueing: modules/resume_processing.md
      - LLM Resume Evaluation: modules/llm_evaluation.md
      - Communication Service: modules/communication.md
      - Feedback Processing: modules/feedback.md
      - Reminder Service: modules/reminders.md
  
  - Future Scope: future-scope.md
